spring:
  datasource:
    url: jdbc:mysql://106.53.227.249:3306/artist?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: Uth%1owxdNutxln2
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    timeout: 6000
    password: 'gE&l@Bic'
    cluster:
      # 获取失败 最大重定向次数
      max-redirects: 3
      nodes:
        - 106.53.227.249:7000
        - 106.53.227.249:7001
        - 106.53.227.249:7002
        - 106.53.227.249:7003
        - 106.53.227.249:7004
        - 106.53.227.249:7005
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 1000
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 5
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1

mybatis:
  mapperLocations: classpath:mapper/*.xml

logging:
  level:
    com.luffy.artist: debug

swagger:
  enabled: true
