spring:
  datasource:
    url: jdbc:mysql://106.53.227.249:3306/artist
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapperLocations: classpath:mapper/*.xml

logging:
  level:
    com.luffy.artist: debug

swagger:
  enabled: true